language: node_js
node_js:
  - "8"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  yarn: true
before_script:
  - npm rebuild
  - yarn build-css
  - yarn start-js &
  - sleep 30
